### ISSUE TITLE
surf1 example

### ISSUE THREAD

**Issue by zoheir1928** [stranskyjan/dem-fem-coupling#9]
Hi Jan,
I am trying to run your example: surf1
When I run the makefile, I get the following error:
I would appreciate you helping me out here.
Zoheir

~/FEMDEM/Installation/_build/install$ make -f makefile all

# set usePolyhedra=True if poly option is set
# use profiler or not
#python -m cProfile -o /tmp/surf1.pro surf1.py
# reset _yade.py script after running
sed -i 's/^usePolyhedra *=.*/usePolyhedra = False/' surf1_yade.py
python surf1_profile.py
Traceback (most recent call last):
  File "surf1_profile.py", line 4, in <module>
    stats = StatsWrapper('/tmp/surf1.pro')
  File "/home/zoheir/FEMDEM/Installation/_build/install/profiler.py", line 12, in __init__
    self.stats = Stats(fName).stats
  File "/usr/lib/python2.7/pstats.py", line 81, in __init__
    self.init(arg)
  File "/usr/lib/python2.7/pstats.py", line 95, in init
    self.load_stats(arg)
  File "/usr/lib/python2.7/pstats.py", line 109, in load_stats
    f = open(arg, 'rb')
IOError: [Errno 2] No such file or directory: '/tmp/surf1.pro'
makefile:56: recipe for target 'profile' failed
make: *** [profile] Error 1

**Comment by stranskyjan** [comment]
sorry, there were commented important lines, thanks for reporting, should work now
cheers
Jan
